spring:
  data:
    mongodb:
      uri: mongodb+srv://janithnirmal29_db_user:test2002@ac-gcjvq7i.5opuupr.mongodb.net/smartcampus?retryWrites=true&w=majority
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            

jwt:
  secret:  mySuperSecureJwtSecretKey1234567890
  expiration: 86400000

app:
  upload-dir: uploads/
  cors:
    allowed-origins: http://localhost:5173,http://localhost:5174
